language: python
python:
  - "3.11"  

cache: pip

install:
  - pip install -r requirements.txt  
  - pip install coveralls


after_script:
  - coveralls

script:
  - black --check .  
  - flake8 --exclude=migrations.
  - coverage run --source=myproject,polls manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "Poll-App"
  env: "poll-app"
  bucket_name: "elasticbeanstalk-us-east-1-156041420494"
  on:
    branch: main
  